# Generated by Django 2.2.2 on 2020-08-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_cord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_cord',
            old_name='city_name',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='city_cord',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City'),
        ),
    ]
