# Generated by Django 2.2 on 2020-08-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200826_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_cord',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City'),
        ),
    ]
